package com.roadnet.apex;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2020-03-15T13:07:07.213-03:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://roadnet.com/apex/", name = "IAdministrationService")
@XmlSeeAlso({org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.ObjectFactory.class, org.datacontract.schemas._2004._07.system_collections.ObjectFactory.class, org.datacontract.schemas._2004._07.system.ObjectFactory.class, com.roadnet.apex.datacontracts.ObjectFactory.class, org.datacontract.schemas._2004._07.roadnet_apex_server_services_administration.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, org.datacontract.schemas._2004._07.roadnet_apex_server_services_routing.ObjectFactory.class, generated.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class, org.datacontract.schemas._2004._07.roadnet_apex_server_services_login.ObjectFactory.class, org.datacontract.schemas._2004._07.roadnet_apex_server_controllers.ObjectFactory.class, org.datacontract.schemas._2004._07.roadnet_apex_server_core.ObjectFactory.class, org.datacontract.schemas._2004._07.roadnet_apex_server_services_query_datawarehouse_roadnet_apex_server_services_query.ObjectFactory.class, org.datacontract.schemas._2004._07.roadnet_apex_server_services_wcfshared.ObjectFactory.class, org.datacontract.schemas._2004._07.roadnet_apex_server_services_wcfshared_datacontracts.ObjectFactory.class, org.datacontract.schemas._2004._07.roadnet_apex_server_services.ObjectFactory.class, ObjectFactory.class, org.datacontract.schemas._2004._07.roadnet_apex_server_core_domain_admin.ObjectFactory.class, org.datacontract.schemas._2004._07.roadnet_apex_server_services_query.ObjectFactory.class, org.datacontract.schemas._2004._07.roadnet_apex_server_services_routing_datacontracts.ObjectFactory.class})
public interface IAdministrationService {

    @WebMethod(operationName = "AttachCustomer", action = "http://roadnet.com/apex/IAdministrationService/AttachCustomer")
    @Action(input = "http://roadnet.com/apex/IAdministrationService/AttachCustomer", output = "http://roadnet.com/apex/IAdministrationService/AttachCustomerResponse", fault = {@FaultAction(className = IAdministrationServiceAttachCustomerListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/AttachCustomerListOf_ValidationFailureFault"), @FaultAction(className = IAdministrationServiceAttachCustomerTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/AttachCustomerTransferErrorCodeFault")})
    @RequestWrapper(localName = "AttachCustomer", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.AttachCustomer")
    @ResponseWrapper(localName = "AttachCustomerResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.AttachCustomerResponse")
    @WebResult(name = "AttachCustomerResult", targetNamespace = "http://roadnet.com/apex/")
    public java.lang.Long attachCustomer(
        @WebParam(name = "parameters", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_administration.AttachCustomerParameters parameters
    ) throws IAdministrationServiceAttachCustomerListOfValidationFailureFaultMessage, IAdministrationServiceAttachCustomerTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "LookupMobileDevices", action = "http://roadnet.com/apex/IAdministrationService/LookupMobileDevices")
    @Action(input = "http://roadnet.com/apex/IAdministrationService/LookupMobileDevices", output = "http://roadnet.com/apex/IAdministrationService/LookupMobileDevicesResponse", fault = {@FaultAction(className = IAdministrationServiceLookupMobileDevicesListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/LookupMobileDevicesListOf_ValidationFailureFault"), @FaultAction(className = IAdministrationServiceLookupMobileDevicesTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/LookupMobileDevicesTransferErrorCodeFault")})
    @RequestWrapper(localName = "LookupMobileDevices", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.LookupMobileDevices")
    @ResponseWrapper(localName = "LookupMobileDevicesResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.LookupMobileDevicesResponse")
    @WebResult(name = "LookupMobileDevicesResult", targetNamespace = "http://roadnet.com/apex/")
    public org.datacontract.schemas._2004._07.roadnet_apex_server_services_administration.DeviceLookupResults lookupMobileDevices(
        @WebParam(name = "parameters", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_administration.DeviceLookupParameters parameters,
        @WebParam(name = "options", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.RetrievalOptions options
    ) throws IAdministrationServiceLookupMobileDevicesListOfValidationFailureFaultMessage, IAdministrationServiceLookupMobileDevicesTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "UpdateCustomerRegions", action = "http://roadnet.com/apex/IAdministrationService/UpdateCustomerRegions")
    @Action(input = "http://roadnet.com/apex/IAdministrationService/UpdateCustomerRegions", output = "http://roadnet.com/apex/IAdministrationService/UpdateCustomerRegionsResponse", fault = {@FaultAction(className = IAdministrationServiceUpdateCustomerRegionsListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/UpdateCustomerRegionsListOf_ValidationFailureFault"), @FaultAction(className = IAdministrationServiceUpdateCustomerRegionsTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/UpdateCustomerRegionsTransferErrorCodeFault")})
    @RequestWrapper(localName = "UpdateCustomerRegions", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.UpdateCustomerRegions")
    @ResponseWrapper(localName = "UpdateCustomerRegionsResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.UpdateCustomerRegionsResponse")
    @WebResult(name = "UpdateCustomerRegionsResult", targetNamespace = "http://roadnet.com/apex/")
    public java.lang.Long updateCustomerRegions(
        @WebParam(name = "parameters", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_administration.UpdateCustomerRegionsParameters parameters
    ) throws IAdministrationServiceUpdateCustomerRegionsListOfValidationFailureFaultMessage, IAdministrationServiceUpdateCustomerRegionsTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "TestCustomerXrsSettings", action = "http://roadnet.com/apex/IAdministrationService/TestCustomerXrsSettings")
    @Action(input = "http://roadnet.com/apex/IAdministrationService/TestCustomerXrsSettings", output = "http://roadnet.com/apex/IAdministrationService/TestCustomerXrsSettingsResponse", fault = {@FaultAction(className = IAdministrationServiceTestCustomerXrsSettingsListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/TestCustomerXrsSettingsListOf_ValidationFailureFault"), @FaultAction(className = IAdministrationServiceTestCustomerXrsSettingsTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/TestCustomerXrsSettingsTransferErrorCodeFault")})
    @RequestWrapper(localName = "TestCustomerXrsSettings", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.TestCustomerXrsSettings")
    @ResponseWrapper(localName = "TestCustomerXrsSettingsResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.TestCustomerXrsSettingsResponse")
    @WebResult(name = "TestCustomerXrsSettingsResult", targetNamespace = "http://roadnet.com/apex/")
    public org.datacontract.schemas._2004._07.roadnet_apex_server_services_administration.TestCustomerXrsSettingsResults testCustomerXrsSettings(
        @WebParam(name = "parameters", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_administration.TestCustomerXrsSettingsParameters parameters
    ) throws IAdministrationServiceTestCustomerXrsSettingsListOfValidationFailureFaultMessage, IAdministrationServiceTestCustomerXrsSettingsTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "MultiRetrieveAdmin", action = "http://roadnet.com/apex/IAdministrationService/MultiRetrieveAdmin")
    @Action(input = "http://roadnet.com/apex/IAdministrationService/MultiRetrieveAdmin", output = "http://roadnet.com/apex/IAdministrationService/MultiRetrieveAdminResponse", fault = {@FaultAction(className = IAdministrationServiceMultiRetrieveAdminListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/MultiRetrieveAdminListOf_ValidationFailureFault"), @FaultAction(className = IAdministrationServiceMultiRetrieveAdminTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/MultiRetrieveAdminTransferErrorCodeFault")})
    @RequestWrapper(localName = "MultiRetrieveAdmin", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.MultiRetrieveAdmin")
    @ResponseWrapper(localName = "MultiRetrieveAdminResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.MultiRetrieveAdminResponse")
    @WebResult(name = "MultiRetrieveAdminResult", targetNamespace = "http://roadnet.com/apex/")
    public com.roadnet.apex.datacontracts.ArrayOfRetrievalResults multiRetrieveAdmin(
        @WebParam(name = "options", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.ArrayOfRetrievalOptions options
    ) throws IAdministrationServiceMultiRetrieveAdminListOfValidationFailureFaultMessage, IAdministrationServiceMultiRetrieveAdminTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "RetrieveCustomersWithXrsServiceUrl", action = "http://roadnet.com/apex/IAdministrationService/RetrieveCustomersWithXrsServiceUrl")
    @Action(input = "http://roadnet.com/apex/IAdministrationService/RetrieveCustomersWithXrsServiceUrl", output = "http://roadnet.com/apex/IAdministrationService/RetrieveCustomersWithXrsServiceUrlResponse", fault = {@FaultAction(className = IAdministrationServiceRetrieveCustomersWithXrsServiceUrlListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/RetrieveCustomersWithXrsServiceUrlListOf_ValidationFailureFault"), @FaultAction(className = IAdministrationServiceRetrieveCustomersWithXrsServiceUrlTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/RetrieveCustomersWithXrsServiceUrlTransferErrorCodeFault")})
    @RequestWrapper(localName = "RetrieveCustomersWithXrsServiceUrl", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveCustomersWithXrsServiceUrl")
    @ResponseWrapper(localName = "RetrieveCustomersWithXrsServiceUrlResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveCustomersWithXrsServiceUrlResponse")
    @WebResult(name = "RetrieveCustomersWithXrsServiceUrlResult", targetNamespace = "http://roadnet.com/apex/")
    public org.datacontract.schemas._2004._07.roadnet_apex_server_services_administration.ArrayOfCustomer retrieveCustomersWithXrsServiceUrl(
        @WebParam(name = "filterForCompliance", targetNamespace = "http://roadnet.com/apex/")
        java.lang.Boolean filterForCompliance
    ) throws IAdministrationServiceRetrieveCustomersWithXrsServiceUrlListOfValidationFailureFaultMessage, IAdministrationServiceRetrieveCustomersWithXrsServiceUrlTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "RetrieveClientApplicationVersion", action = "http://roadnet.com/apex/IAdministrationService/RetrieveClientApplicationVersion")
    @Action(input = "http://roadnet.com/apex/IAdministrationService/RetrieveClientApplicationVersion", output = "http://roadnet.com/apex/IAdministrationService/RetrieveClientApplicationVersionResponse", fault = {@FaultAction(className = IAdministrationServiceRetrieveClientApplicationVersionListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/RetrieveClientApplicationVersionListOf_ValidationFailureFault"), @FaultAction(className = IAdministrationServiceRetrieveClientApplicationVersionTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/RetrieveClientApplicationVersionTransferErrorCodeFault")})
    @RequestWrapper(localName = "RetrieveClientApplicationVersion", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveClientApplicationVersion")
    @ResponseWrapper(localName = "RetrieveClientApplicationVersionResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveClientApplicationVersionResponse")
    @WebResult(name = "RetrieveClientApplicationVersionResult", targetNamespace = "http://roadnet.com/apex/")
    public com.roadnet.apex.datacontracts.ClientApplicationVersion retrieveClientApplicationVersion(
        @WebParam(name = "applicationIdentifier", targetNamespace = "http://roadnet.com/apex/")
        java.lang.String applicationIdentifier,
        @WebParam(name = "customerPkey", targetNamespace = "http://roadnet.com/apex/")
        java.lang.Long customerPkey
    ) throws IAdministrationServiceRetrieveClientApplicationVersionListOfValidationFailureFaultMessage, IAdministrationServiceRetrieveClientApplicationVersionTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "RetrieveQueuedMatrixBuildRequestMessages", action = "http://roadnet.com/apex/IAdministrationService/RetrieveQueuedMatrixBuildRequestMessages")
    @Action(input = "http://roadnet.com/apex/IAdministrationService/RetrieveQueuedMatrixBuildRequestMessages", output = "http://roadnet.com/apex/IAdministrationService/RetrieveQueuedMatrixBuildRequestMessagesResponse", fault = {@FaultAction(className = IAdministrationServiceRetrieveQueuedMatrixBuildRequestMessagesListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/RetrieveQueuedMatrixBuildRequestMessagesListOf_ValidationFailureFault"), @FaultAction(className = IAdministrationServiceRetrieveQueuedMatrixBuildRequestMessagesTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/RetrieveQueuedMatrixBuildRequestMessagesTransferErrorCodeFault")})
    @RequestWrapper(localName = "RetrieveQueuedMatrixBuildRequestMessages", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveQueuedMatrixBuildRequestMessages")
    @ResponseWrapper(localName = "RetrieveQueuedMatrixBuildRequestMessagesResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveQueuedMatrixBuildRequestMessagesResponse")
    @WebResult(name = "RetrieveQueuedMatrixBuildRequestMessagesResult", targetNamespace = "http://roadnet.com/apex/")
    public org.datacontract.schemas._2004._07.roadnet_apex_server_services_administration.MatrixBuildRequestMessages retrieveQueuedMatrixBuildRequestMessages() throws IAdministrationServiceRetrieveQueuedMatrixBuildRequestMessagesListOfValidationFailureFaultMessage, IAdministrationServiceRetrieveQueuedMatrixBuildRequestMessagesTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "ProcessXrsMigrationWorkbook", action = "http://roadnet.com/apex/IAdministrationService/ProcessXrsMigrationWorkbook")
    @Action(input = "http://roadnet.com/apex/IAdministrationService/ProcessXrsMigrationWorkbook", output = "http://roadnet.com/apex/IAdministrationService/ProcessXrsMigrationWorkbookResponse", fault = {@FaultAction(className = IAdministrationServiceProcessXrsMigrationWorkbookListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/ProcessXrsMigrationWorkbookListOf_ValidationFailureFault"), @FaultAction(className = IAdministrationServiceProcessXrsMigrationWorkbookTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/ProcessXrsMigrationWorkbookTransferErrorCodeFault")})
    @RequestWrapper(localName = "ProcessXrsMigrationWorkbook", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.ProcessXrsMigrationWorkbook")
    @ResponseWrapper(localName = "ProcessXrsMigrationWorkbookResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.ProcessXrsMigrationWorkbookResponse")
    @WebResult(name = "ProcessXrsMigrationWorkbookResult", targetNamespace = "http://roadnet.com/apex/")
    public java.lang.Long processXrsMigrationWorkbook(
        @WebParam(name = "parameters", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_administration.XrsMigrationParameters parameters
    ) throws IAdministrationServiceProcessXrsMigrationWorkbookListOfValidationFailureFaultMessage, IAdministrationServiceProcessXrsMigrationWorkbookTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "ImportOBD2DiagnosticsTroubleCodes", action = "http://roadnet.com/apex/IAdministrationService/ImportOBD2DiagnosticsTroubleCodes")
    @Action(input = "http://roadnet.com/apex/IAdministrationService/ImportOBD2DiagnosticsTroubleCodes", output = "http://roadnet.com/apex/IAdministrationService/ImportOBD2DiagnosticsTroubleCodesResponse", fault = {@FaultAction(className = IAdministrationServiceImportOBD2DiagnosticsTroubleCodesListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/ImportOBD2DiagnosticsTroubleCodesListOf_ValidationFailureFault"), @FaultAction(className = IAdministrationServiceImportOBD2DiagnosticsTroubleCodesTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/ImportOBD2DiagnosticsTroubleCodesTransferErrorCodeFault")})
    @RequestWrapper(localName = "ImportOBD2DiagnosticsTroubleCodes", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.ImportOBD2DiagnosticsTroubleCodes")
    @ResponseWrapper(localName = "ImportOBD2DiagnosticsTroubleCodesResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.ImportOBD2DiagnosticsTroubleCodesResponse")
    @WebResult(name = "ImportOBD2DiagnosticsTroubleCodesResult", targetNamespace = "http://roadnet.com/apex/")
    public java.lang.Long importOBD2DiagnosticsTroubleCodes(
        @WebParam(name = "parameters", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_administration.ImportOBD2DiagnosticTroubleCodesParameters parameters
    ) throws IAdministrationServiceImportOBD2DiagnosticsTroubleCodesListOfValidationFailureFaultMessage, IAdministrationServiceImportOBD2DiagnosticsTroubleCodesTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "RetrieveAdminReports", action = "http://roadnet.com/apex/IAdministrationService/RetrieveAdminReports")
    @Action(input = "http://roadnet.com/apex/IAdministrationService/RetrieveAdminReports", output = "http://roadnet.com/apex/IAdministrationService/RetrieveAdminReportsResponse", fault = {@FaultAction(className = IAdministrationServiceRetrieveAdminReportsListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/RetrieveAdminReportsListOf_ValidationFailureFault"), @FaultAction(className = IAdministrationServiceRetrieveAdminReportsTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/RetrieveAdminReportsTransferErrorCodeFault")})
    @RequestWrapper(localName = "RetrieveAdminReports", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveAdminReports")
    @ResponseWrapper(localName = "RetrieveAdminReportsResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveAdminReportsResponse")
    @WebResult(name = "RetrieveAdminReportsResult", targetNamespace = "http://roadnet.com/apex/")
    public org.datacontract.schemas._2004._07.roadnet_apex_server_services_administration.ArrayOfAdminReport retrieveAdminReports() throws IAdministrationServiceRetrieveAdminReportsListOfValidationFailureFaultMessage, IAdministrationServiceRetrieveAdminReportsTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "RetrieveCustomReports", action = "http://roadnet.com/apex/IAdministrationService/RetrieveCustomReports")
    @Action(input = "http://roadnet.com/apex/IAdministrationService/RetrieveCustomReports", output = "http://roadnet.com/apex/IAdministrationService/RetrieveCustomReportsResponse", fault = {@FaultAction(className = IAdministrationServiceRetrieveCustomReportsListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/RetrieveCustomReportsListOf_ValidationFailureFault"), @FaultAction(className = IAdministrationServiceRetrieveCustomReportsTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/RetrieveCustomReportsTransferErrorCodeFault")})
    @RequestWrapper(localName = "RetrieveCustomReports", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveCustomReports")
    @ResponseWrapper(localName = "RetrieveCustomReportsResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveCustomReportsResponse")
    @WebResult(name = "RetrieveCustomReportsResult", targetNamespace = "http://roadnet.com/apex/")
    public com.roadnet.apex.datacontracts.ArrayOfReport retrieveCustomReports(
        @WebParam(name = "customerEntityKey", targetNamespace = "http://roadnet.com/apex/")
        java.lang.Long customerEntityKey,
        @WebParam(name = "reportOptions", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.ReportPropertyOptions reportOptions
    ) throws IAdministrationServiceRetrieveCustomReportsListOfValidationFailureFaultMessage, IAdministrationServiceRetrieveCustomReportsTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "ToggleMatrixBuildEnabledForCustomerRegions", action = "http://roadnet.com/apex/IAdministrationService/ToggleMatrixBuildEnabledForCustomerRegions")
    @Action(input = "http://roadnet.com/apex/IAdministrationService/ToggleMatrixBuildEnabledForCustomerRegions", output = "http://roadnet.com/apex/IAdministrationService/ToggleMatrixBuildEnabledForCustomerRegionsResponse", fault = {@FaultAction(className = IAdministrationServiceToggleMatrixBuildEnabledForCustomerRegionsListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/ToggleMatrixBuildEnabledForCustomerRegionsListOf_ValidationFailureFault"), @FaultAction(className = IAdministrationServiceToggleMatrixBuildEnabledForCustomerRegionsTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/ToggleMatrixBuildEnabledForCustomerRegionsTransferErrorCodeFault")})
    @RequestWrapper(localName = "ToggleMatrixBuildEnabledForCustomerRegions", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.ToggleMatrixBuildEnabledForCustomerRegions")
    @ResponseWrapper(localName = "ToggleMatrixBuildEnabledForCustomerRegionsResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.ToggleMatrixBuildEnabledForCustomerRegionsResponse")
    @WebResult(name = "ToggleMatrixBuildEnabledForCustomerRegionsResult", targetNamespace = "http://roadnet.com/apex/")
    public com.roadnet.apex.datacontracts.ArrayOfSaveResult toggleMatrixBuildEnabledForCustomerRegions(
        @WebParam(name = "customerEntityKey", targetNamespace = "http://roadnet.com/apex/")
        java.lang.Long customerEntityKey,
        @WebParam(name = "regionEntityKeys", targetNamespace = "http://roadnet.com/apex/")
        com.microsoft.schemas._2003._10.serialization.arrays.ArrayOflong regionEntityKeys
    ) throws IAdministrationServiceToggleMatrixBuildEnabledForCustomerRegionsListOfValidationFailureFaultMessage, IAdministrationServiceToggleMatrixBuildEnabledForCustomerRegionsTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "InitializeDataWarehouse", action = "http://roadnet.com/apex/IAdministrationService/InitializeDataWarehouse")
    @Action(input = "http://roadnet.com/apex/IAdministrationService/InitializeDataWarehouse", output = "http://roadnet.com/apex/IAdministrationService/InitializeDataWarehouseResponse", fault = {@FaultAction(className = IAdministrationServiceInitializeDataWarehouseListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/InitializeDataWarehouseListOf_ValidationFailureFault"), @FaultAction(className = IAdministrationServiceInitializeDataWarehouseTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/InitializeDataWarehouseTransferErrorCodeFault")})
    @RequestWrapper(localName = "InitializeDataWarehouse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.InitializeDataWarehouse")
    @ResponseWrapper(localName = "InitializeDataWarehouseResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.InitializeDataWarehouseResponse")
    @WebResult(name = "InitializeDataWarehouseResult", targetNamespace = "http://roadnet.com/apex/")
    public java.lang.Long initializeDataWarehouse(
        @WebParam(name = "parameters", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_administration.InitializeDataWarehouseParameters parameters
    ) throws IAdministrationServiceInitializeDataWarehouseListOfValidationFailureFaultMessage, IAdministrationServiceInitializeDataWarehouseTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "RetrieveCustomReport", action = "http://roadnet.com/apex/IAdministrationService/RetrieveCustomReport")
    @Action(input = "http://roadnet.com/apex/IAdministrationService/RetrieveCustomReport", output = "http://roadnet.com/apex/IAdministrationService/RetrieveCustomReportResponse", fault = {@FaultAction(className = IAdministrationServiceRetrieveCustomReportListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/RetrieveCustomReportListOf_ValidationFailureFault"), @FaultAction(className = IAdministrationServiceRetrieveCustomReportTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/RetrieveCustomReportTransferErrorCodeFault")})
    @RequestWrapper(localName = "RetrieveCustomReport", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveCustomReport")
    @ResponseWrapper(localName = "RetrieveCustomReportResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveCustomReportResponse")
    @WebResult(name = "RetrieveCustomReportResult", targetNamespace = "http://roadnet.com/apex/")
    public com.roadnet.apex.datacontracts.Report retrieveCustomReport(
        @WebParam(name = "entityKey", targetNamespace = "http://roadnet.com/apex/")
        java.lang.Long entityKey,
        @WebParam(name = "customerEntityKey", targetNamespace = "http://roadnet.com/apex/")
        java.lang.Long customerEntityKey,
        @WebParam(name = "reportOptions", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.ReportPropertyOptions reportOptions
    ) throws IAdministrationServiceRetrieveCustomReportListOfValidationFailureFaultMessage, IAdministrationServiceRetrieveCustomReportTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "RetrieveCustomerRegionMatrixStatistics", action = "http://roadnet.com/apex/IAdministrationService/RetrieveCustomerRegionMatrixStatistics")
    @Action(input = "http://roadnet.com/apex/IAdministrationService/RetrieveCustomerRegionMatrixStatistics", output = "http://roadnet.com/apex/IAdministrationService/RetrieveCustomerRegionMatrixStatisticsResponse", fault = {@FaultAction(className = IAdministrationServiceRetrieveCustomerRegionMatrixStatisticsListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/RetrieveCustomerRegionMatrixStatisticsListOf_ValidationFailureFault"), @FaultAction(className = IAdministrationServiceRetrieveCustomerRegionMatrixStatisticsTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/RetrieveCustomerRegionMatrixStatisticsTransferErrorCodeFault")})
    @RequestWrapper(localName = "RetrieveCustomerRegionMatrixStatistics", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveCustomerRegionMatrixStatistics")
    @ResponseWrapper(localName = "RetrieveCustomerRegionMatrixStatisticsResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveCustomerRegionMatrixStatisticsResponse")
    @WebResult(name = "RetrieveCustomerRegionMatrixStatisticsResult", targetNamespace = "http://roadnet.com/apex/")
    public org.datacontract.schemas._2004._07.roadnet_apex_server_services_administration.CustomerRegionMatrixStatisticsResults retrieveCustomerRegionMatrixStatistics(
        @WebParam(name = "statsDate", targetNamespace = "http://roadnet.com/apex/")
        javax.xml.datatype.XMLGregorianCalendar statsDate
    ) throws IAdministrationServiceRetrieveCustomerRegionMatrixStatisticsListOfValidationFailureFaultMessage, IAdministrationServiceRetrieveCustomerRegionMatrixStatisticsTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "CreateCustomer", action = "http://roadnet.com/apex/IAdministrationService/CreateCustomer")
    @Action(input = "http://roadnet.com/apex/IAdministrationService/CreateCustomer", output = "http://roadnet.com/apex/IAdministrationService/CreateCustomerResponse", fault = {@FaultAction(className = IAdministrationServiceCreateCustomerListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/CreateCustomerListOf_ValidationFailureFault"), @FaultAction(className = IAdministrationServiceCreateCustomerTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/CreateCustomerTransferErrorCodeFault")})
    @RequestWrapper(localName = "CreateCustomer", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.CreateCustomer")
    @ResponseWrapper(localName = "CreateCustomerResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.CreateCustomerResponse")
    @WebResult(name = "CreateCustomerResult", targetNamespace = "http://roadnet.com/apex/")
    public java.lang.Long createCustomer(
        @WebParam(name = "parameters", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_administration.CreateCustomerParameters parameters
    ) throws IAdministrationServiceCreateCustomerListOfValidationFailureFaultMessage, IAdministrationServiceCreateCustomerTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "RetrieveCurrentlyBuildingMatrixBuildResultsFile", action = "http://roadnet.com/apex/IAdministrationService/RetrieveCurrentlyBuildingMatrixBuildResultsFile")
    @Action(input = "http://roadnet.com/apex/IAdministrationService/RetrieveCurrentlyBuildingMatrixBuildResultsFile", output = "http://roadnet.com/apex/IAdministrationService/RetrieveCurrentlyBuildingMatrixBuildResultsFileResponse", fault = {@FaultAction(className = IAdministrationServiceRetrieveCurrentlyBuildingMatrixBuildResultsFileListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/RetrieveCurrentlyBuildingMatrixBuildResultsFileListOf_ValidationFailureFault"), @FaultAction(className = IAdministrationServiceRetrieveCurrentlyBuildingMatrixBuildResultsFileTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/RetrieveCurrentlyBuildingMatrixBuildResultsFileTransferErrorCodeFault")})
    @RequestWrapper(localName = "RetrieveCurrentlyBuildingMatrixBuildResultsFile", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveCurrentlyBuildingMatrixBuildResultsFile")
    @ResponseWrapper(localName = "RetrieveCurrentlyBuildingMatrixBuildResultsFileResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveCurrentlyBuildingMatrixBuildResultsFileResponse")
    @WebResult(name = "RetrieveCurrentlyBuildingMatrixBuildResultsFileResult", targetNamespace = "http://roadnet.com/apex/")
    public org.datacontract.schemas._2004._07.roadnet_apex_server_services_administration.MatrixBuildResults retrieveCurrentlyBuildingMatrixBuildResultsFile() throws IAdministrationServiceRetrieveCurrentlyBuildingMatrixBuildResultsFileListOfValidationFailureFaultMessage, IAdministrationServiceRetrieveCurrentlyBuildingMatrixBuildResultsFileTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "RetrieveClientApplicationVersions", action = "http://roadnet.com/apex/IAdministrationService/RetrieveClientApplicationVersions")
    @Action(input = "http://roadnet.com/apex/IAdministrationService/RetrieveClientApplicationVersions", output = "http://roadnet.com/apex/IAdministrationService/RetrieveClientApplicationVersionsResponse", fault = {@FaultAction(className = IAdministrationServiceRetrieveClientApplicationVersionsListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/RetrieveClientApplicationVersionsListOf_ValidationFailureFault"), @FaultAction(className = IAdministrationServiceRetrieveClientApplicationVersionsTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/RetrieveClientApplicationVersionsTransferErrorCodeFault")})
    @RequestWrapper(localName = "RetrieveClientApplicationVersions", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveClientApplicationVersions")
    @ResponseWrapper(localName = "RetrieveClientApplicationVersionsResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveClientApplicationVersionsResponse")
    @WebResult(name = "RetrieveClientApplicationVersionsResult", targetNamespace = "http://roadnet.com/apex/")
    public com.roadnet.apex.datacontracts.ArrayOfClientApplicationVersion retrieveClientApplicationVersions(
        @WebParam(name = "applicationIdentifier", targetNamespace = "http://roadnet.com/apex/")
        java.lang.String applicationIdentifier
    ) throws IAdministrationServiceRetrieveClientApplicationVersionsListOfValidationFailureFaultMessage, IAdministrationServiceRetrieveClientApplicationVersionsTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "UploadCustomReport", action = "http://roadnet.com/apex/IAdministrationService/UploadCustomReport")
    @Action(input = "http://roadnet.com/apex/IAdministrationService/UploadCustomReport", output = "http://roadnet.com/apex/IAdministrationService/UploadCustomReportResponse", fault = {@FaultAction(className = IAdministrationServiceUploadCustomReportListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/UploadCustomReportListOf_ValidationFailureFault"), @FaultAction(className = IAdministrationServiceUploadCustomReportTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/UploadCustomReportTransferErrorCodeFault")})
    @RequestWrapper(localName = "UploadCustomReport", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.UploadCustomReport")
    @ResponseWrapper(localName = "UploadCustomReportResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.UploadCustomReportResponse")
    @WebResult(name = "UploadCustomReportResult", targetNamespace = "http://roadnet.com/apex/")
    public org.datacontract.schemas._2004._07.roadnet_apex_server_services_administration.UploadCustomReportResults uploadCustomReport(
        @WebParam(name = "parameters", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_administration.UploadCustomReportParameters parameters
    ) throws IAdministrationServiceUploadCustomReportListOfValidationFailureFaultMessage, IAdministrationServiceUploadCustomReportTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "StartRdcMigration", action = "http://roadnet.com/apex/IAdministrationService/StartRdcMigration")
    @Action(input = "http://roadnet.com/apex/IAdministrationService/StartRdcMigration", output = "http://roadnet.com/apex/IAdministrationService/StartRdcMigrationResponse", fault = {@FaultAction(className = IAdministrationServiceStartRdcMigrationListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/StartRdcMigrationListOf_ValidationFailureFault"), @FaultAction(className = IAdministrationServiceStartRdcMigrationTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/StartRdcMigrationTransferErrorCodeFault")})
    @RequestWrapper(localName = "StartRdcMigration", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.StartRdcMigration")
    @ResponseWrapper(localName = "StartRdcMigrationResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.StartRdcMigrationResponse")
    @WebResult(name = "StartRdcMigrationResult", targetNamespace = "http://roadnet.com/apex/")
    public java.lang.Long startRdcMigration(
        @WebParam(name = "parameters", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_administration.RdcMigrationParameters parameters
    ) throws IAdministrationServiceStartRdcMigrationListOfValidationFailureFaultMessage, IAdministrationServiceStartRdcMigrationTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "UpdateConvertedCustomer", action = "http://roadnet.com/apex/IAdministrationService/UpdateConvertedCustomer")
    @Action(input = "http://roadnet.com/apex/IAdministrationService/UpdateConvertedCustomer", output = "http://roadnet.com/apex/IAdministrationService/UpdateConvertedCustomerResponse", fault = {@FaultAction(className = IAdministrationServiceUpdateConvertedCustomerListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/UpdateConvertedCustomerListOf_ValidationFailureFault"), @FaultAction(className = IAdministrationServiceUpdateConvertedCustomerTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/UpdateConvertedCustomerTransferErrorCodeFault")})
    @RequestWrapper(localName = "UpdateConvertedCustomer", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.UpdateConvertedCustomer")
    @ResponseWrapper(localName = "UpdateConvertedCustomerResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.UpdateConvertedCustomerResponse")
    @WebResult(name = "UpdateConvertedCustomerResult", targetNamespace = "http://roadnet.com/apex/")
    public java.lang.Long updateConvertedCustomer(
        @WebParam(name = "customerEntityKey", targetNamespace = "http://roadnet.com/apex/")
        java.lang.Long customerEntityKey
    ) throws IAdministrationServiceUpdateConvertedCustomerListOfValidationFailureFaultMessage, IAdministrationServiceUpdateConvertedCustomerTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "GenerateRdcMigrationExcelWorkbook", action = "http://roadnet.com/apex/IAdministrationService/GenerateRdcMigrationExcelWorkbook")
    @Action(input = "http://roadnet.com/apex/IAdministrationService/GenerateRdcMigrationExcelWorkbook", output = "http://roadnet.com/apex/IAdministrationService/GenerateRdcMigrationExcelWorkbookResponse", fault = {@FaultAction(className = IAdministrationServiceGenerateRdcMigrationExcelWorkbookListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/GenerateRdcMigrationExcelWorkbookListOf_ValidationFailureFault"), @FaultAction(className = IAdministrationServiceGenerateRdcMigrationExcelWorkbookTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/GenerateRdcMigrationExcelWorkbookTransferErrorCodeFault")})
    @RequestWrapper(localName = "GenerateRdcMigrationExcelWorkbook", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.GenerateRdcMigrationExcelWorkbook")
    @ResponseWrapper(localName = "GenerateRdcMigrationExcelWorkbookResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.GenerateRdcMigrationExcelWorkbookResponse")
    @WebResult(name = "GenerateRdcMigrationExcelWorkbookResult", targetNamespace = "http://roadnet.com/apex/")
    public java.lang.Long generateRdcMigrationExcelWorkbook(
        @WebParam(name = "customerEntityKey", targetNamespace = "http://roadnet.com/apex/")
        java.lang.Long customerEntityKey
    ) throws IAdministrationServiceGenerateRdcMigrationExcelWorkbookListOfValidationFailureFaultMessage, IAdministrationServiceGenerateRdcMigrationExcelWorkbookTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "SaveAdmin", action = "http://roadnet.com/apex/IAdministrationService/SaveAdmin")
    @Action(input = "http://roadnet.com/apex/IAdministrationService/SaveAdmin", output = "http://roadnet.com/apex/IAdministrationService/SaveAdminResponse", fault = {@FaultAction(className = IAdministrationServiceSaveAdminListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/SaveAdminListOf_ValidationFailureFault"), @FaultAction(className = IAdministrationServiceSaveAdminTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/SaveAdminTransferErrorCodeFault")})
    @RequestWrapper(localName = "SaveAdmin", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.SaveAdmin")
    @ResponseWrapper(localName = "SaveAdminResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.SaveAdminResponse")
    @WebResult(name = "SaveAdminResult", targetNamespace = "http://roadnet.com/apex/")
    public com.roadnet.apex.datacontracts.ArrayOfSaveResult saveAdmin(
        @WebParam(name = "objects", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.ArrayOfAggregateRootEntity objects,
        @WebParam(name = "options", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.SaveOptions options
    ) throws IAdministrationServiceSaveAdminListOfValidationFailureFaultMessage, IAdministrationServiceSaveAdminTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "RetrieveDataWarehouseIntegrationStatus", action = "http://roadnet.com/apex/IAdministrationService/RetrieveDataWarehouseIntegrationStatus")
    @Action(input = "http://roadnet.com/apex/IAdministrationService/RetrieveDataWarehouseIntegrationStatus", output = "http://roadnet.com/apex/IAdministrationService/RetrieveDataWarehouseIntegrationStatusResponse", fault = {@FaultAction(className = IAdministrationServiceRetrieveDataWarehouseIntegrationStatusListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/RetrieveDataWarehouseIntegrationStatusListOf_ValidationFailureFault"), @FaultAction(className = IAdministrationServiceRetrieveDataWarehouseIntegrationStatusTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/RetrieveDataWarehouseIntegrationStatusTransferErrorCodeFault")})
    @RequestWrapper(localName = "RetrieveDataWarehouseIntegrationStatus", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveDataWarehouseIntegrationStatus")
    @ResponseWrapper(localName = "RetrieveDataWarehouseIntegrationStatusResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveDataWarehouseIntegrationStatusResponse")
    @WebResult(name = "RetrieveDataWarehouseIntegrationStatusResult", targetNamespace = "http://roadnet.com/apex/")
    public org.datacontract.schemas._2004._07.roadnet_apex_server_services_wcfshared_datacontracts.DataWarehouseIntegrationStatus retrieveDataWarehouseIntegrationStatus(
        @WebParam(name = "customerEntityKey", targetNamespace = "http://roadnet.com/apex/")
        java.lang.Long customerEntityKey
    ) throws IAdministrationServiceRetrieveDataWarehouseIntegrationStatusListOfValidationFailureFaultMessage, IAdministrationServiceRetrieveDataWarehouseIntegrationStatusTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "ResetDataWarehouseIntegrationStatus", action = "http://roadnet.com/apex/IAdministrationService/ResetDataWarehouseIntegrationStatus")
    @Action(input = "http://roadnet.com/apex/IAdministrationService/ResetDataWarehouseIntegrationStatus", output = "http://roadnet.com/apex/IAdministrationService/ResetDataWarehouseIntegrationStatusResponse", fault = {@FaultAction(className = IAdministrationServiceResetDataWarehouseIntegrationStatusListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/ResetDataWarehouseIntegrationStatusListOf_ValidationFailureFault"), @FaultAction(className = IAdministrationServiceResetDataWarehouseIntegrationStatusTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/ResetDataWarehouseIntegrationStatusTransferErrorCodeFault")})
    @RequestWrapper(localName = "ResetDataWarehouseIntegrationStatus", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.ResetDataWarehouseIntegrationStatus")
    @ResponseWrapper(localName = "ResetDataWarehouseIntegrationStatusResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.ResetDataWarehouseIntegrationStatusResponse")
    @WebResult(name = "ResetDataWarehouseIntegrationStatusResult", targetNamespace = "http://roadnet.com/apex/")
    public org.datacontract.schemas._2004._07.roadnet_apex_server_services_wcfshared_datacontracts.DataWarehouseIntegrationStatus resetDataWarehouseIntegrationStatus(
        @WebParam(name = "customerEntityKey", targetNamespace = "http://roadnet.com/apex/")
        java.lang.Long customerEntityKey
    ) throws IAdministrationServiceResetDataWarehouseIntegrationStatusListOfValidationFailureFaultMessage, IAdministrationServiceResetDataWarehouseIntegrationStatusTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "SendNewUserEmail", action = "http://roadnet.com/apex/IAdministrationService/SendNewUserEmail")
    @Action(input = "http://roadnet.com/apex/IAdministrationService/SendNewUserEmail", output = "http://roadnet.com/apex/IAdministrationService/SendNewUserEmailResponse", fault = {@FaultAction(className = IAdministrationServiceSendNewUserEmailListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/SendNewUserEmailListOf_ValidationFailureFault"), @FaultAction(className = IAdministrationServiceSendNewUserEmailTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/SendNewUserEmailTransferErrorCodeFault")})
    @RequestWrapper(localName = "SendNewUserEmail", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.SendNewUserEmail")
    @ResponseWrapper(localName = "SendNewUserEmailResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.SendNewUserEmailResponse")
    @WebResult(name = "SendNewUserEmailResult", targetNamespace = "http://roadnet.com/apex/")
    public com.roadnet.apex.datacontracts.ArrayOfResetPasswordResult sendNewUserEmail(
        @WebParam(name = "customerEntityKey", targetNamespace = "http://roadnet.com/apex/")
        java.lang.Long customerEntityKey,
        @WebParam(name = "userEntityKeys", targetNamespace = "http://roadnet.com/apex/")
        com.microsoft.schemas._2003._10.serialization.arrays.ArrayOflong userEntityKeys
    ) throws IAdministrationServiceSendNewUserEmailListOfValidationFailureFaultMessage, IAdministrationServiceSendNewUserEmailTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "SwitchDataWarehouseMappingMode", action = "http://roadnet.com/apex/IAdministrationService/SwitchDataWarehouseMappingMode")
    @Action(input = "http://roadnet.com/apex/IAdministrationService/SwitchDataWarehouseMappingMode", output = "http://roadnet.com/apex/IAdministrationService/SwitchDataWarehouseMappingModeResponse", fault = {@FaultAction(className = IAdministrationServiceSwitchDataWarehouseMappingModeListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/SwitchDataWarehouseMappingModeListOf_ValidationFailureFault"), @FaultAction(className = IAdministrationServiceSwitchDataWarehouseMappingModeTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/SwitchDataWarehouseMappingModeTransferErrorCodeFault")})
    @RequestWrapper(localName = "SwitchDataWarehouseMappingMode", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.SwitchDataWarehouseMappingMode")
    @ResponseWrapper(localName = "SwitchDataWarehouseMappingModeResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.SwitchDataWarehouseMappingModeResponse")
    @WebResult(name = "SwitchDataWarehouseMappingModeResult", targetNamespace = "http://roadnet.com/apex/")
    public java.lang.Boolean switchDataWarehouseMappingMode(
        @WebParam(name = "customerEntityKey", targetNamespace = "http://roadnet.com/apex/")
        java.lang.Long customerEntityKey
    ) throws IAdministrationServiceSwitchDataWarehouseMappingModeListOfValidationFailureFaultMessage, IAdministrationServiceSwitchDataWarehouseMappingModeTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "RetrieveMatrixBuildResultsFile", action = "http://roadnet.com/apex/IAdministrationService/RetrieveMatrixBuildResultsFile")
    @Action(input = "http://roadnet.com/apex/IAdministrationService/RetrieveMatrixBuildResultsFile", output = "http://roadnet.com/apex/IAdministrationService/RetrieveMatrixBuildResultsFileResponse", fault = {@FaultAction(className = IAdministrationServiceRetrieveMatrixBuildResultsFileListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/RetrieveMatrixBuildResultsFileListOf_ValidationFailureFault"), @FaultAction(className = IAdministrationServiceRetrieveMatrixBuildResultsFileTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/RetrieveMatrixBuildResultsFileTransferErrorCodeFault")})
    @RequestWrapper(localName = "RetrieveMatrixBuildResultsFile", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveMatrixBuildResultsFile")
    @ResponseWrapper(localName = "RetrieveMatrixBuildResultsFileResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveMatrixBuildResultsFileResponse")
    @WebResult(name = "RetrieveMatrixBuildResultsFileResult", targetNamespace = "http://roadnet.com/apex/")
    public org.datacontract.schemas._2004._07.roadnet_apex_server_services_administration.MatrixBuildResults retrieveMatrixBuildResultsFile(
        @WebParam(name = "optionsDto", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_administration.RetrieveMatrixResultsOptions optionsDto
    ) throws IAdministrationServiceRetrieveMatrixBuildResultsFileListOfValidationFailureFaultMessage, IAdministrationServiceRetrieveMatrixBuildResultsFileTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "CreateXrsMigrationWorkbook", action = "http://roadnet.com/apex/IAdministrationService/CreateXrsMigrationWorkbook")
    @Action(input = "http://roadnet.com/apex/IAdministrationService/CreateXrsMigrationWorkbook", output = "http://roadnet.com/apex/IAdministrationService/CreateXrsMigrationWorkbookResponse", fault = {@FaultAction(className = IAdministrationServiceCreateXrsMigrationWorkbookListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/CreateXrsMigrationWorkbookListOf_ValidationFailureFault"), @FaultAction(className = IAdministrationServiceCreateXrsMigrationWorkbookTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/CreateXrsMigrationWorkbookTransferErrorCodeFault")})
    @RequestWrapper(localName = "CreateXrsMigrationWorkbook", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.CreateXrsMigrationWorkbook")
    @ResponseWrapper(localName = "CreateXrsMigrationWorkbookResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.CreateXrsMigrationWorkbookResponse")
    @WebResult(name = "CreateXrsMigrationWorkbookResult", targetNamespace = "http://roadnet.com/apex/")
    public java.lang.Long createXrsMigrationWorkbook(
        @WebParam(name = "customerEntityKey", targetNamespace = "http://roadnet.com/apex/")
        java.lang.Long customerEntityKey
    ) throws IAdministrationServiceCreateXrsMigrationWorkbookListOfValidationFailureFaultMessage, IAdministrationServiceCreateXrsMigrationWorkbookTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "RetrieveMatrixResults", action = "http://roadnet.com/apex/IAdministrationService/RetrieveMatrixResults")
    @Action(input = "http://roadnet.com/apex/IAdministrationService/RetrieveMatrixResults", output = "http://roadnet.com/apex/IAdministrationService/RetrieveMatrixResultsResponse", fault = {@FaultAction(className = IAdministrationServiceRetrieveMatrixResultsListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/RetrieveMatrixResultsListOf_ValidationFailureFault"), @FaultAction(className = IAdministrationServiceRetrieveMatrixResultsTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/RetrieveMatrixResultsTransferErrorCodeFault")})
    @RequestWrapper(localName = "RetrieveMatrixResults", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveMatrixResults")
    @ResponseWrapper(localName = "RetrieveMatrixResultsResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveMatrixResultsResponse")
    @WebResult(name = "RetrieveMatrixResultsResult", targetNamespace = "http://roadnet.com/apex/")
    public org.datacontract.schemas._2004._07.roadnet_apex_server_services_administration.ArrayOfMatrixBuildResultExt retrieveMatrixResults(
        @WebParam(name = "optionsDto", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_administration.RetrieveMatrixResultsOptions optionsDto
    ) throws IAdministrationServiceRetrieveMatrixResultsListOfValidationFailureFaultMessage, IAdministrationServiceRetrieveMatrixResultsTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "RetrieveAdmin", action = "http://roadnet.com/apex/IAdministrationService/RetrieveAdmin")
    @Action(input = "http://roadnet.com/apex/IAdministrationService/RetrieveAdmin", output = "http://roadnet.com/apex/IAdministrationService/RetrieveAdminResponse", fault = {@FaultAction(className = IAdministrationServiceRetrieveAdminListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/RetrieveAdminListOf_ValidationFailureFault"), @FaultAction(className = IAdministrationServiceRetrieveAdminTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/RetrieveAdminTransferErrorCodeFault")})
    @RequestWrapper(localName = "RetrieveAdmin", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveAdmin")
    @ResponseWrapper(localName = "RetrieveAdminResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveAdminResponse")
    @WebResult(name = "RetrieveAdminResult", targetNamespace = "http://roadnet.com/apex/")
    public com.roadnet.apex.datacontracts.RetrievalResults retrieveAdmin(
        @WebParam(name = "options", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.RetrievalOptions options
    ) throws IAdministrationServiceRetrieveAdminListOfValidationFailureFaultMessage, IAdministrationServiceRetrieveAdminTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "CreateTopLevelComplianceRegion", action = "http://roadnet.com/apex/IAdministrationService/CreateTopLevelComplianceRegion")
    @Action(input = "http://roadnet.com/apex/IAdministrationService/CreateTopLevelComplianceRegion", output = "http://roadnet.com/apex/IAdministrationService/CreateTopLevelComplianceRegionResponse", fault = {@FaultAction(className = IAdministrationServiceCreateTopLevelComplianceRegionListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/CreateTopLevelComplianceRegionListOf_ValidationFailureFault"), @FaultAction(className = IAdministrationServiceCreateTopLevelComplianceRegionTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/CreateTopLevelComplianceRegionTransferErrorCodeFault")})
    @RequestWrapper(localName = "CreateTopLevelComplianceRegion", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.CreateTopLevelComplianceRegion")
    @ResponseWrapper(localName = "CreateTopLevelComplianceRegionResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.CreateTopLevelComplianceRegionResponse")
    @WebResult(name = "CreateTopLevelComplianceRegionResult", targetNamespace = "http://roadnet.com/apex/")
    public com.roadnet.apex.datacontracts.SaveResult createTopLevelComplianceRegion(
        @WebParam(name = "customerEntityKey", targetNamespace = "http://roadnet.com/apex/")
        java.lang.Long customerEntityKey
    ) throws IAdministrationServiceCreateTopLevelComplianceRegionListOfValidationFailureFaultMessage, IAdministrationServiceCreateTopLevelComplianceRegionTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "RetrieveGeneralReleaseClientApplicationVersion", action = "http://roadnet.com/apex/IAdministrationService/RetrieveGeneralReleaseClientApplicationVersion")
    @Action(input = "http://roadnet.com/apex/IAdministrationService/RetrieveGeneralReleaseClientApplicationVersion", output = "http://roadnet.com/apex/IAdministrationService/RetrieveGeneralReleaseClientApplicationVersionResponse", fault = {@FaultAction(className = IAdministrationServiceRetrieveGeneralReleaseClientApplicationVersionListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/RetrieveGeneralReleaseClientApplicationVersionListOf_ValidationFailureFault"), @FaultAction(className = IAdministrationServiceRetrieveGeneralReleaseClientApplicationVersionTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/RetrieveGeneralReleaseClientApplicationVersionTransferErrorCodeFault")})
    @RequestWrapper(localName = "RetrieveGeneralReleaseClientApplicationVersion", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveGeneralReleaseClientApplicationVersion")
    @ResponseWrapper(localName = "RetrieveGeneralReleaseClientApplicationVersionResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveGeneralReleaseClientApplicationVersionResponse")
    @WebResult(name = "RetrieveGeneralReleaseClientApplicationVersionResult", targetNamespace = "http://roadnet.com/apex/")
    public com.roadnet.apex.datacontracts.ClientApplicationVersion retrieveGeneralReleaseClientApplicationVersion(
        @WebParam(name = "applicationIdentifier", targetNamespace = "http://roadnet.com/apex/")
        java.lang.String applicationIdentifier
    ) throws IAdministrationServiceRetrieveGeneralReleaseClientApplicationVersionListOfValidationFailureFaultMessage, IAdministrationServiceRetrieveGeneralReleaseClientApplicationVersionTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "ShadowProduction", action = "http://roadnet.com/apex/IAdministrationService/ShadowProduction")
    @Action(input = "http://roadnet.com/apex/IAdministrationService/ShadowProduction", output = "http://roadnet.com/apex/IAdministrationService/ShadowProductionResponse", fault = {@FaultAction(className = IAdministrationServiceShadowProductionListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/ShadowProductionListOf_ValidationFailureFault"), @FaultAction(className = IAdministrationServiceShadowProductionTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/ShadowProductionTransferErrorCodeFault")})
    @RequestWrapper(localName = "ShadowProduction", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.ShadowProduction")
    @ResponseWrapper(localName = "ShadowProductionResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.ShadowProductionResponse")
    @WebResult(name = "ShadowProductionResult", targetNamespace = "http://roadnet.com/apex/")
    public java.lang.Long shadowProduction(
        @WebParam(name = "parameters", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_administration.ShadowProductionParameters parameters
    ) throws IAdministrationServiceShadowProductionListOfValidationFailureFaultMessage, IAdministrationServiceShadowProductionTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "FindCustomerUsageData", action = "http://roadnet.com/apex/IAdministrationService/FindCustomerUsageData")
    @Action(input = "http://roadnet.com/apex/IAdministrationService/FindCustomerUsageData", output = "http://roadnet.com/apex/IAdministrationService/FindCustomerUsageDataResponse", fault = {@FaultAction(className = IAdministrationServiceFindCustomerUsageDataListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/FindCustomerUsageDataListOf_ValidationFailureFault"), @FaultAction(className = IAdministrationServiceFindCustomerUsageDataTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/FindCustomerUsageDataTransferErrorCodeFault")})
    @RequestWrapper(localName = "FindCustomerUsageData", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.FindCustomerUsageData")
    @ResponseWrapper(localName = "FindCustomerUsageDataResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.FindCustomerUsageDataResponse")
    @WebResult(name = "FindCustomerUsageDataResult", targetNamespace = "http://roadnet.com/apex/")
    public java.lang.Long findCustomerUsageData(
        @WebParam(name = "parameters", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_administration.FindCustomersParameters parameters
    ) throws IAdministrationServiceFindCustomerUsageDataListOfValidationFailureFaultMessage, IAdministrationServiceFindCustomerUsageDataTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "CreateTopLevelComplianceRegion2", action = "http://roadnet.com/apex/IAdministrationService/CreateTopLevelComplianceRegion2")
    @Action(input = "http://roadnet.com/apex/IAdministrationService/CreateTopLevelComplianceRegion2", output = "http://roadnet.com/apex/IAdministrationService/CreateTopLevelComplianceRegion2Response", fault = {@FaultAction(className = IAdministrationServiceCreateTopLevelComplianceRegion2ListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/CreateTopLevelComplianceRegion2ListOf_ValidationFailureFault"), @FaultAction(className = IAdministrationServiceCreateTopLevelComplianceRegion2TransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/CreateTopLevelComplianceRegion2TransferErrorCodeFault")})
    @RequestWrapper(localName = "CreateTopLevelComplianceRegion2", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.CreateTopLevelComplianceRegion2")
    @ResponseWrapper(localName = "CreateTopLevelComplianceRegion2Response", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.CreateTopLevelComplianceRegion2Response")
    @WebResult(name = "CreateTopLevelComplianceRegion2Result", targetNamespace = "http://roadnet.com/apex/")
    public com.roadnet.apex.datacontracts.SaveResult createTopLevelComplianceRegion2(
        @WebParam(name = "customerEntityKey", targetNamespace = "http://roadnet.com/apex/")
        java.lang.Long customerEntityKey,
        @WebParam(name = "isEnablingRegionHierarchy", targetNamespace = "http://roadnet.com/apex/")
        java.lang.Boolean isEnablingRegionHierarchy
    ) throws IAdministrationServiceCreateTopLevelComplianceRegion2ListOfValidationFailureFaultMessage, IAdministrationServiceCreateTopLevelComplianceRegion2TransferErrorCodeFaultMessage;

    @WebMethod(operationName = "RetrieveQueuedMatrixBuildRequestResults", action = "http://roadnet.com/apex/IAdministrationService/RetrieveQueuedMatrixBuildRequestResults")
    @Action(input = "http://roadnet.com/apex/IAdministrationService/RetrieveQueuedMatrixBuildRequestResults", output = "http://roadnet.com/apex/IAdministrationService/RetrieveQueuedMatrixBuildRequestResultsResponse", fault = {@FaultAction(className = IAdministrationServiceRetrieveQueuedMatrixBuildRequestResultsListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/RetrieveQueuedMatrixBuildRequestResultsListOf_ValidationFailureFault"), @FaultAction(className = IAdministrationServiceRetrieveQueuedMatrixBuildRequestResultsTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/RetrieveQueuedMatrixBuildRequestResultsTransferErrorCodeFault")})
    @RequestWrapper(localName = "RetrieveQueuedMatrixBuildRequestResults", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveQueuedMatrixBuildRequestResults")
    @ResponseWrapper(localName = "RetrieveQueuedMatrixBuildRequestResultsResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveQueuedMatrixBuildRequestResultsResponse")
    @WebResult(name = "RetrieveQueuedMatrixBuildRequestResultsResult", targetNamespace = "http://roadnet.com/apex/")
    public org.datacontract.schemas._2004._07.roadnet_apex_server_services_administration.MatrixBuildRequestResults retrieveQueuedMatrixBuildRequestResults() throws IAdministrationServiceRetrieveQueuedMatrixBuildRequestResultsListOfValidationFailureFaultMessage, IAdministrationServiceRetrieveQueuedMatrixBuildRequestResultsTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "CreateDatabase", action = "http://roadnet.com/apex/IAdministrationService/CreateDatabase")
    @Action(input = "http://roadnet.com/apex/IAdministrationService/CreateDatabase", output = "http://roadnet.com/apex/IAdministrationService/CreateDatabaseResponse", fault = {@FaultAction(className = IAdministrationServiceCreateDatabaseListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/CreateDatabaseListOf_ValidationFailureFault"), @FaultAction(className = IAdministrationServiceCreateDatabaseTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/CreateDatabaseTransferErrorCodeFault")})
    @RequestWrapper(localName = "CreateDatabase", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.CreateDatabase")
    @ResponseWrapper(localName = "CreateDatabaseResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.CreateDatabaseResponse")
    @WebResult(name = "CreateDatabaseResult", targetNamespace = "http://roadnet.com/apex/")
    public java.lang.Long createDatabase(
        @WebParam(name = "parameters", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_administration.CreateDatabaseParameters parameters
    ) throws IAdministrationServiceCreateDatabaseListOfValidationFailureFaultMessage, IAdministrationServiceCreateDatabaseTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "RetrieveCustomerLoggingSettings", action = "http://roadnet.com/apex/IAdministrationService/RetrieveCustomerLoggingSettings")
    @Action(input = "http://roadnet.com/apex/IAdministrationService/RetrieveCustomerLoggingSettings", output = "http://roadnet.com/apex/IAdministrationService/RetrieveCustomerLoggingSettingsResponse", fault = {@FaultAction(className = IAdministrationServiceRetrieveCustomerLoggingSettingsListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/RetrieveCustomerLoggingSettingsListOf_ValidationFailureFault"), @FaultAction(className = IAdministrationServiceRetrieveCustomerLoggingSettingsTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IAdministrationService/RetrieveCustomerLoggingSettingsTransferErrorCodeFault")})
    @RequestWrapper(localName = "RetrieveCustomerLoggingSettings", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveCustomerLoggingSettings")
    @ResponseWrapper(localName = "RetrieveCustomerLoggingSettingsResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveCustomerLoggingSettingsResponse")
    @WebResult(name = "RetrieveCustomerLoggingSettingsResult", targetNamespace = "http://roadnet.com/apex/")
    public org.datacontract.schemas._2004._07.roadnet_apex_server_services_administration.LoggingSettings retrieveCustomerLoggingSettings(
        @WebParam(name = "customerEntityKey", targetNamespace = "http://roadnet.com/apex/")
        java.lang.Long customerEntityKey
    ) throws IAdministrationServiceRetrieveCustomerLoggingSettingsListOfValidationFailureFaultMessage, IAdministrationServiceRetrieveCustomerLoggingSettingsTransferErrorCodeFaultMessage;
}
