package com.roadnet.apex;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2020-03-15T13:07:07.416-03:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://roadnet.com/apex/", name = "IMappingService")
@XmlSeeAlso({org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.ObjectFactory.class, org.datacontract.schemas._2004._07.system_collections.ObjectFactory.class, org.datacontract.schemas._2004._07.system.ObjectFactory.class, com.roadnet.apex.datacontracts.ObjectFactory.class, org.datacontract.schemas._2004._07.roadnet_apex_server_services_administration.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, org.datacontract.schemas._2004._07.roadnet_apex_server_services_routing.ObjectFactory.class, generated.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class, org.datacontract.schemas._2004._07.roadnet_apex_server_services_login.ObjectFactory.class, org.datacontract.schemas._2004._07.roadnet_apex_server_controllers.ObjectFactory.class, org.datacontract.schemas._2004._07.roadnet_apex_server_core.ObjectFactory.class, org.datacontract.schemas._2004._07.roadnet_apex_server_services_query_datawarehouse_roadnet_apex_server_services_query.ObjectFactory.class, org.datacontract.schemas._2004._07.roadnet_apex_server_services_wcfshared.ObjectFactory.class, org.datacontract.schemas._2004._07.roadnet_apex_server_services_wcfshared_datacontracts.ObjectFactory.class, org.datacontract.schemas._2004._07.roadnet_apex_server_services.ObjectFactory.class, ObjectFactory.class, org.datacontract.schemas._2004._07.roadnet_apex_server_core_domain_admin.ObjectFactory.class, org.datacontract.schemas._2004._07.roadnet_apex_server_services_query.ObjectFactory.class, org.datacontract.schemas._2004._07.roadnet_apex_server_services_routing_datacontracts.ObjectFactory.class})
public interface IMappingService {

    @WebMethod(operationName = "Geocode", action = "http://roadnet.com/apex/IMappingService/Geocode")
    @Action(input = "http://roadnet.com/apex/IMappingService/Geocode", output = "http://roadnet.com/apex/IMappingService/GeocodeResponse", fault = {@FaultAction(className = IMappingServiceGeocodeListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/GeocodeListOf_ValidationFailureFault"), @FaultAction(className = IMappingServiceGeocodeTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/GeocodeTransferErrorCodeFault")})
    @RequestWrapper(localName = "Geocode", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.Geocode")
    @ResponseWrapper(localName = "GeocodeResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.GeocodeResponse")
    @WebResult(name = "GeocodeResult", targetNamespace = "http://roadnet.com/apex/")
    public com.roadnet.apex.datacontracts.ArrayOfGeocodeResult geocode(
        @WebParam(name = "regionContext", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.RegionContext regionContext,
        @WebParam(name = "criteria", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.GeocodeCriteria criteria,
        @WebParam(name = "options", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.GeocodeOptions options
    ) throws IMappingServiceGeocodeListOfValidationFailureFaultMessage, IMappingServiceGeocodeTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "UpdateNode", action = "http://roadnet.com/apex/IMappingService/UpdateNode")
    @Action(input = "http://roadnet.com/apex/IMappingService/UpdateNode", output = "http://roadnet.com/apex/IMappingService/UpdateNodeResponse", fault = {@FaultAction(className = IMappingServiceUpdateNodeListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/UpdateNodeListOf_ValidationFailureFault"), @FaultAction(className = IMappingServiceUpdateNodeTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/UpdateNodeTransferErrorCodeFault")})
    @RequestWrapper(localName = "UpdateNode", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.UpdateNode")
    @ResponseWrapper(localName = "UpdateNodeResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.UpdateNodeResponse")
    public void updateNode(
        @WebParam(name = "regionContext", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.RegionContext regionContext,
        @WebParam(name = "criteria", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.UpdateNodeCriteria criteria
    ) throws IMappingServiceUpdateNodeListOfValidationFailureFaultMessage, IMappingServiceUpdateNodeTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "MapSync", action = "http://roadnet.com/apex/IMappingService/MapSync")
    @Action(input = "http://roadnet.com/apex/IMappingService/MapSync", output = "http://roadnet.com/apex/IMappingService/MapSyncResponse", fault = {@FaultAction(className = IMappingServiceMapSyncListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/MapSyncListOf_ValidationFailureFault"), @FaultAction(className = IMappingServiceMapSyncTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/MapSyncTransferErrorCodeFault")})
    @RequestWrapper(localName = "MapSync", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.MapSync")
    @ResponseWrapper(localName = "MapSyncResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.MapSyncResponse")
    public void mapSync(
        @WebParam(name = "regionContext", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.RegionContext regionContext,
        @WebParam(name = "criteria", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.MapSyncCriteria criteria,
        @WebParam(name = "options", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.MapSyncOptions options
    ) throws IMappingServiceMapSyncListOfValidationFailureFaultMessage, IMappingServiceMapSyncTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "RetrieveTravelModel", action = "http://roadnet.com/apex/IMappingService/RetrieveTravelModel")
    @Action(input = "http://roadnet.com/apex/IMappingService/RetrieveTravelModel", output = "http://roadnet.com/apex/IMappingService/RetrieveTravelModelResponse", fault = {@FaultAction(className = IMappingServiceRetrieveTravelModelListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/RetrieveTravelModelListOf_ValidationFailureFault"), @FaultAction(className = IMappingServiceRetrieveTravelModelTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/RetrieveTravelModelTransferErrorCodeFault")})
    @RequestWrapper(localName = "RetrieveTravelModel", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveTravelModel")
    @ResponseWrapper(localName = "RetrieveTravelModelResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveTravelModelResponse")
    @WebResult(name = "RetrieveTravelModelResult", targetNamespace = "http://roadnet.com/apex/")
    public org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.RetrieveTravelModelResults retrieveTravelModel(
        @WebParam(name = "regionContext", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.RegionContext regionContext
    ) throws IMappingServiceRetrieveTravelModelListOfValidationFailureFaultMessage, IMappingServiceRetrieveTravelModelTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "StartGeocodeJob", action = "http://roadnet.com/apex/IMappingService/StartGeocodeJob")
    @Action(input = "http://roadnet.com/apex/IMappingService/StartGeocodeJob", output = "http://roadnet.com/apex/IMappingService/StartGeocodeJobResponse", fault = {@FaultAction(className = IMappingServiceStartGeocodeJobListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/StartGeocodeJobListOf_ValidationFailureFault"), @FaultAction(className = IMappingServiceStartGeocodeJobTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/StartGeocodeJobTransferErrorCodeFault")})
    @RequestWrapper(localName = "StartGeocodeJob", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.StartGeocodeJob")
    @ResponseWrapper(localName = "StartGeocodeJobResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.StartGeocodeJobResponse")
    @WebResult(name = "StartGeocodeJobResult", targetNamespace = "http://roadnet.com/apex/")
    public java.lang.Long startGeocodeJob(
        @WebParam(name = "regionContext", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.RegionContext regionContext,
        @WebParam(name = "criteria", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.GeocodeCriteria criteria,
        @WebParam(name = "options", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.GeocodeOptions options
    ) throws IMappingServiceStartGeocodeJobListOfValidationFailureFaultMessage, IMappingServiceStartGeocodeJobTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "RetrieveNodes", action = "http://roadnet.com/apex/IMappingService/RetrieveNodes")
    @Action(input = "http://roadnet.com/apex/IMappingService/RetrieveNodes", output = "http://roadnet.com/apex/IMappingService/RetrieveNodesResponse", fault = {@FaultAction(className = IMappingServiceRetrieveNodesListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/RetrieveNodesListOf_ValidationFailureFault"), @FaultAction(className = IMappingServiceRetrieveNodesTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/RetrieveNodesTransferErrorCodeFault")})
    @RequestWrapper(localName = "RetrieveNodes", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveNodes")
    @ResponseWrapper(localName = "RetrieveNodesResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveNodesResponse")
    @WebResult(name = "RetrieveNodesResult", targetNamespace = "http://roadnet.com/apex/")
    public org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.RetrieveNodesResults retrieveNodes(
        @WebParam(name = "regionContext", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.RegionContext regionContext,
        @WebParam(name = "criteria", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.RetrieveNodesCriteria criteria,
        @WebParam(name = "options", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.RetrieveNodesOptions options
    ) throws IMappingServiceRetrieveNodesListOfValidationFailureFaultMessage, IMappingServiceRetrieveNodesTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "StartGeocodeLocationsJob", action = "http://roadnet.com/apex/IMappingService/StartGeocodeLocationsJob")
    @Action(input = "http://roadnet.com/apex/IMappingService/StartGeocodeLocationsJob", output = "http://roadnet.com/apex/IMappingService/StartGeocodeLocationsJobResponse", fault = {@FaultAction(className = IMappingServiceStartGeocodeLocationsJobListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/StartGeocodeLocationsJobListOf_ValidationFailureFault"), @FaultAction(className = IMappingServiceStartGeocodeLocationsJobTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/StartGeocodeLocationsJobTransferErrorCodeFault")})
    @RequestWrapper(localName = "StartGeocodeLocationsJob", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.StartGeocodeLocationsJob")
    @ResponseWrapper(localName = "StartGeocodeLocationsJobResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.StartGeocodeLocationsJobResponse")
    @WebResult(name = "StartGeocodeLocationsJobResult", targetNamespace = "http://roadnet.com/apex/")
    public java.lang.Long startGeocodeLocationsJob(
        @WebParam(name = "regionContext", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.RegionContext regionContext,
        @WebParam(name = "LocationEntityKeys", targetNamespace = "http://roadnet.com/apex/")
        com.microsoft.schemas._2003._10.serialization.arrays.ArrayOflong locationEntityKeys
    ) throws IMappingServiceStartGeocodeLocationsJobListOfValidationFailureFaultMessage, IMappingServiceStartGeocodeLocationsJobTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "PerformSearch", action = "http://roadnet.com/apex/IMappingService/PerformSearch")
    @Action(input = "http://roadnet.com/apex/IMappingService/PerformSearch", output = "http://roadnet.com/apex/IMappingService/PerformSearchResponse", fault = {@FaultAction(className = IMappingServicePerformSearchListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/PerformSearchListOf_ValidationFailureFault"), @FaultAction(className = IMappingServicePerformSearchTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/PerformSearchTransferErrorCodeFault")})
    @RequestWrapper(localName = "PerformSearch", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.PerformSearch")
    @ResponseWrapper(localName = "PerformSearchResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.PerformSearchResponse")
    @WebResult(name = "PerformSearchResult", targetNamespace = "http://roadnet.com/apex/")
    public org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.MapLocalSearchResult performSearch(
        @WebParam(name = "regionContext", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.RegionContext regionContext,
        @WebParam(name = "criteria", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.MapLocalSearchCriteria criteria,
        @WebParam(name = "options", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.MapLocalSearchOptions options
    ) throws IMappingServicePerformSearchListOfValidationFailureFaultMessage, IMappingServicePerformSearchTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "RetrieveRouteShields", action = "http://roadnet.com/apex/IMappingService/RetrieveRouteShields")
    @Action(input = "http://roadnet.com/apex/IMappingService/RetrieveRouteShields", output = "http://roadnet.com/apex/IMappingService/RetrieveRouteShieldsResponse", fault = {@FaultAction(className = IMappingServiceRetrieveRouteShieldsListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/RetrieveRouteShieldsListOf_ValidationFailureFault"), @FaultAction(className = IMappingServiceRetrieveRouteShieldsTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/RetrieveRouteShieldsTransferErrorCodeFault")})
    @RequestWrapper(localName = "RetrieveRouteShields", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveRouteShields")
    @ResponseWrapper(localName = "RetrieveRouteShieldsResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveRouteShieldsResponse")
    @WebResult(name = "RetrieveRouteShieldsResult", targetNamespace = "http://roadnet.com/apex/")
    public org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.ArrayOfRouteShield retrieveRouteShields() throws IMappingServiceRetrieveRouteShieldsListOfValidationFailureFaultMessage, IMappingServiceRetrieveRouteShieldsTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "UpdateTravelModel", action = "http://roadnet.com/apex/IMappingService/UpdateTravelModel")
    @Action(input = "http://roadnet.com/apex/IMappingService/UpdateTravelModel", output = "http://roadnet.com/apex/IMappingService/UpdateTravelModelResponse", fault = {@FaultAction(className = IMappingServiceUpdateTravelModelListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/UpdateTravelModelListOf_ValidationFailureFault"), @FaultAction(className = IMappingServiceUpdateTravelModelTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/UpdateTravelModelTransferErrorCodeFault")})
    @RequestWrapper(localName = "UpdateTravelModel", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.UpdateTravelModel")
    @ResponseWrapper(localName = "UpdateTravelModelResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.UpdateTravelModelResponse")
    public void updateTravelModel(
        @WebParam(name = "regionContext", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.RegionContext regionContext,
        @WebParam(name = "travelModelDto", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.NetworkTravelModel travelModelDto
    ) throws IMappingServiceUpdateTravelModelListOfValidationFailureFaultMessage, IMappingServiceUpdateTravelModelTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "RetrieveFullMapEdits", action = "http://roadnet.com/apex/IMappingService/RetrieveFullMapEdits")
    @Action(input = "http://roadnet.com/apex/IMappingService/RetrieveFullMapEdits", output = "http://roadnet.com/apex/IMappingService/RetrieveFullMapEditsResponse", fault = {@FaultAction(className = IMappingServiceRetrieveFullMapEditsListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/RetrieveFullMapEditsListOf_ValidationFailureFault"), @FaultAction(className = IMappingServiceRetrieveFullMapEditsTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/RetrieveFullMapEditsTransferErrorCodeFault")})
    @RequestWrapper(localName = "RetrieveFullMapEdits", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveFullMapEdits")
    @ResponseWrapper(localName = "RetrieveFullMapEditsResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveFullMapEditsResponse")
    @WebResult(name = "RetrieveFullMapEditsResult", targetNamespace = "http://roadnet.com/apex/")
    public org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.RetrieveFullMapEditsResult retrieveFullMapEdits(
        @WebParam(name = "regionContext", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.RegionContext regionContext,
        @WebParam(name = "firstChangeVersion", targetNamespace = "http://roadnet.com/apex/")
        java.lang.Integer firstChangeVersion
    ) throws IMappingServiceRetrieveFullMapEditsListOfValidationFailureFaultMessage, IMappingServiceRetrieveFullMapEditsTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "PopulateArcs", action = "http://roadnet.com/apex/IMappingService/PopulateArcs")
    @Action(input = "http://roadnet.com/apex/IMappingService/PopulateArcs", output = "http://roadnet.com/apex/IMappingService/PopulateArcsResponse", fault = {@FaultAction(className = IMappingServicePopulateArcsListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/PopulateArcsListOf_ValidationFailureFault"), @FaultAction(className = IMappingServicePopulateArcsTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/PopulateArcsTransferErrorCodeFault")})
    @RequestWrapper(localName = "PopulateArcs", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.PopulateArcs")
    @ResponseWrapper(localName = "PopulateArcsResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.PopulateArcsResponse")
    @WebResult(name = "PopulateArcsResult", targetNamespace = "http://roadnet.com/apex/")
    public org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.ArrayOfPopulateArcResult populateArcs(
        @WebParam(name = "regionContext", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.RegionContext regionContext,
        @WebParam(name = "networkIDs", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.ArrayOfNetworkID networkIDs,
        @WebParam(name = "options", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.PopulateArcsOptions options
    ) throws IMappingServicePopulateArcsListOfValidationFailureFaultMessage, IMappingServicePopulateArcsTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "RetrieveNodesDetail", action = "http://roadnet.com/apex/IMappingService/RetrieveNodesDetail")
    @Action(input = "http://roadnet.com/apex/IMappingService/RetrieveNodesDetail", output = "http://roadnet.com/apex/IMappingService/RetrieveNodesDetailResponse", fault = {@FaultAction(className = IMappingServiceRetrieveNodesDetailListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/RetrieveNodesDetailListOf_ValidationFailureFault"), @FaultAction(className = IMappingServiceRetrieveNodesDetailTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/RetrieveNodesDetailTransferErrorCodeFault")})
    @RequestWrapper(localName = "RetrieveNodesDetail", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveNodesDetail")
    @ResponseWrapper(localName = "RetrieveNodesDetailResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveNodesDetailResponse")
    @WebResult(name = "RetrieveNodesDetailResult", targetNamespace = "http://roadnet.com/apex/")
    public org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.RetrieveNodesDetailResults retrieveNodesDetail(
        @WebParam(name = "regionContext", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.RegionContext regionContext,
        @WebParam(name = "criteria", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.RetrieveNodesDetailCriteria criteria,
        @WebParam(name = "options", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.RetrieveNodesDetailOptions options
    ) throws IMappingServiceRetrieveNodesDetailListOfValidationFailureFaultMessage, IMappingServiceRetrieveNodesDetailTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "RetrievePositionTextList", action = "http://roadnet.com/apex/IMappingService/RetrievePositionTextList")
    @Action(input = "http://roadnet.com/apex/IMappingService/RetrievePositionTextList", output = "http://roadnet.com/apex/IMappingService/RetrievePositionTextListResponse", fault = {@FaultAction(className = IMappingServiceRetrievePositionTextListListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/RetrievePositionTextListListOf_ValidationFailureFault"), @FaultAction(className = IMappingServiceRetrievePositionTextListTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/RetrievePositionTextListTransferErrorCodeFault")})
    @RequestWrapper(localName = "RetrievePositionTextList", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrievePositionTextList")
    @ResponseWrapper(localName = "RetrievePositionTextListResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrievePositionTextListResponse")
    @WebResult(name = "RetrievePositionTextListResult", targetNamespace = "http://roadnet.com/apex/")
    public com.roadnet.apex.datacontracts.PositionTextListResult retrievePositionTextList(
        @WebParam(name = "regionContext", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.RegionContext regionContext,
        @WebParam(name = "coordinates", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.ArrayOfCoordinate coordinates,
        @WebParam(name = "options", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.RetrievePositionTextOptions options
    ) throws IMappingServiceRetrievePositionTextListListOfValidationFailureFaultMessage, IMappingServiceRetrievePositionTextListTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "CalculateDistanceByJurisdiction", action = "http://roadnet.com/apex/IMappingService/CalculateDistanceByJurisdiction")
    @Action(input = "http://roadnet.com/apex/IMappingService/CalculateDistanceByJurisdiction", output = "http://roadnet.com/apex/IMappingService/CalculateDistanceByJurisdictionResponse", fault = {@FaultAction(className = IMappingServiceCalculateDistanceByJurisdictionListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/CalculateDistanceByJurisdictionListOf_ValidationFailureFault"), @FaultAction(className = IMappingServiceCalculateDistanceByJurisdictionTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/CalculateDistanceByJurisdictionTransferErrorCodeFault")})
    @RequestWrapper(localName = "CalculateDistanceByJurisdiction", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.CalculateDistanceByJurisdiction")
    @ResponseWrapper(localName = "CalculateDistanceByJurisdictionResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.CalculateDistanceByJurisdictionResponse")
    @WebResult(name = "CalculateDistanceByJurisdictionResult", targetNamespace = "http://roadnet.com/apex/")
    public org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.CalculateDistanceByJurisdictionResult calculateDistanceByJurisdiction(
        @WebParam(name = "regionContext", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.RegionContext regionContext,
        @WebParam(name = "fromCoordinate", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.Coordinate fromCoordinate,
        @WebParam(name = "toCoordinate", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.Coordinate toCoordinate,
        @WebParam(name = "options", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.CalculateDistanceByJurisdictionOptions options
    ) throws IMappingServiceCalculateDistanceByJurisdictionListOfValidationFailureFaultMessage, IMappingServiceCalculateDistanceByJurisdictionTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "GenerateTravelPath", action = "http://roadnet.com/apex/IMappingService/GenerateTravelPath")
    @Action(input = "http://roadnet.com/apex/IMappingService/GenerateTravelPath", output = "http://roadnet.com/apex/IMappingService/GenerateTravelPathResponse", fault = {@FaultAction(className = IMappingServiceGenerateTravelPathListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/GenerateTravelPathListOf_ValidationFailureFault"), @FaultAction(className = IMappingServiceGenerateTravelPathTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/GenerateTravelPathTransferErrorCodeFault")})
    @RequestWrapper(localName = "GenerateTravelPath", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.GenerateTravelPath")
    @ResponseWrapper(localName = "GenerateTravelPathResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.GenerateTravelPathResponse")
    @WebResult(name = "GenerateTravelPathResult", targetNamespace = "http://roadnet.com/apex/")
    public com.roadnet.apex.datacontracts.TravelPathResult generateTravelPath(
        @WebParam(name = "regionContext", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.RegionContext regionContext,
        @WebParam(name = "options", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.GenerateTravelPathOptions options
    ) throws IMappingServiceGenerateTravelPathListOfValidationFailureFaultMessage, IMappingServiceGenerateTravelPathTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "UpdateTravelPolygon", action = "http://roadnet.com/apex/IMappingService/UpdateTravelPolygon")
    @Action(input = "http://roadnet.com/apex/IMappingService/UpdateTravelPolygon", output = "http://roadnet.com/apex/IMappingService/UpdateTravelPolygonResponse", fault = {@FaultAction(className = IMappingServiceUpdateTravelPolygonListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/UpdateTravelPolygonListOf_ValidationFailureFault"), @FaultAction(className = IMappingServiceUpdateTravelPolygonTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/UpdateTravelPolygonTransferErrorCodeFault")})
    @RequestWrapper(localName = "UpdateTravelPolygon", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.UpdateTravelPolygon")
    @ResponseWrapper(localName = "UpdateTravelPolygonResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.UpdateTravelPolygonResponse")
    @WebResult(name = "UpdateTravelPolygonResult", targetNamespace = "http://roadnet.com/apex/")
    public org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.UpdateTravelPolygonResult updateTravelPolygon(
        @WebParam(name = "regionContext", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.RegionContext regionContext,
        @WebParam(name = "travelPolygon", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.NetworkTravelPolygon travelPolygon,
        @WebParam(name = "options", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.UpdateTravelPolygonOptions options
    ) throws IMappingServiceUpdateTravelPolygonListOfValidationFailureFaultMessage, IMappingServiceUpdateTravelPolygonTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "RetrieveEditOperations", action = "http://roadnet.com/apex/IMappingService/RetrieveEditOperations")
    @Action(input = "http://roadnet.com/apex/IMappingService/RetrieveEditOperations", output = "http://roadnet.com/apex/IMappingService/RetrieveEditOperationsResponse", fault = {@FaultAction(className = IMappingServiceRetrieveEditOperationsListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/RetrieveEditOperationsListOf_ValidationFailureFault"), @FaultAction(className = IMappingServiceRetrieveEditOperationsTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/RetrieveEditOperationsTransferErrorCodeFault")})
    @RequestWrapper(localName = "RetrieveEditOperations", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveEditOperations")
    @ResponseWrapper(localName = "RetrieveEditOperationsResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveEditOperationsResponse")
    @WebResult(name = "RetrieveEditOperationsResult", targetNamespace = "http://roadnet.com/apex/")
    public org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.RetrieveEditOperationsResult retrieveEditOperations(
        @WebParam(name = "regionContext", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.RegionContext regionContext,
        @WebParam(name = "criteria", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.RetrieveEditOperationsCriteria criteria,
        @WebParam(name = "options", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.RetrieveEditOperationsOptions options
    ) throws IMappingServiceRetrieveEditOperationsListOfValidationFailureFaultMessage, IMappingServiceRetrieveEditOperationsTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "RetrieveArcs", action = "http://roadnet.com/apex/IMappingService/RetrieveArcs")
    @Action(input = "http://roadnet.com/apex/IMappingService/RetrieveArcs", output = "http://roadnet.com/apex/IMappingService/RetrieveArcsResponse", fault = {@FaultAction(className = IMappingServiceRetrieveArcsListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/RetrieveArcsListOf_ValidationFailureFault"), @FaultAction(className = IMappingServiceRetrieveArcsTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/RetrieveArcsTransferErrorCodeFault")})
    @RequestWrapper(localName = "RetrieveArcs", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveArcs")
    @ResponseWrapper(localName = "RetrieveArcsResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveArcsResponse")
    @WebResult(name = "RetrieveArcsResult", targetNamespace = "http://roadnet.com/apex/")
    public org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.RetrieveArcsResults retrieveArcs(
        @WebParam(name = "regionContext", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.RegionContext regionContext,
        @WebParam(name = "criteria", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.RetrieveArcsCriteria criteria,
        @WebParam(name = "options", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.RetrieveArcsOptions options
    ) throws IMappingServiceRetrieveArcsListOfValidationFailureFaultMessage, IMappingServiceRetrieveArcsTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "RetrievePositionText", action = "http://roadnet.com/apex/IMappingService/RetrievePositionText")
    @Action(input = "http://roadnet.com/apex/IMappingService/RetrievePositionText", output = "http://roadnet.com/apex/IMappingService/RetrievePositionTextResponse", fault = {@FaultAction(className = IMappingServiceRetrievePositionTextListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/RetrievePositionTextListOf_ValidationFailureFault"), @FaultAction(className = IMappingServiceRetrievePositionTextTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/RetrievePositionTextTransferErrorCodeFault")})
    @RequestWrapper(localName = "RetrievePositionText", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrievePositionText")
    @ResponseWrapper(localName = "RetrievePositionTextResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrievePositionTextResponse")
    @WebResult(name = "RetrievePositionTextResult", targetNamespace = "http://roadnet.com/apex/")
    public com.roadnet.apex.datacontracts.RetrievePositionTextResult retrievePositionText(
        @WebParam(name = "regionContext", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.RegionContext regionContext,
        @WebParam(name = "coordinate", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.Coordinate coordinate,
        @WebParam(name = "options", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.RetrievePositionTextOptions options
    ) throws IMappingServiceRetrievePositionTextListOfValidationFailureFaultMessage, IMappingServiceRetrievePositionTextTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "ProcessCommunityEditRequest", action = "http://roadnet.com/apex/IMappingService/ProcessCommunityEditRequest")
    @Action(input = "http://roadnet.com/apex/IMappingService/ProcessCommunityEditRequest", output = "http://roadnet.com/apex/IMappingService/ProcessCommunityEditRequestResponse", fault = {@FaultAction(className = IMappingServiceProcessCommunityEditRequestListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/ProcessCommunityEditRequestListOf_ValidationFailureFault"), @FaultAction(className = IMappingServiceProcessCommunityEditRequestTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/ProcessCommunityEditRequestTransferErrorCodeFault")})
    @RequestWrapper(localName = "ProcessCommunityEditRequest", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.ProcessCommunityEditRequest")
    @ResponseWrapper(localName = "ProcessCommunityEditRequestResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.ProcessCommunityEditRequestResponse")
    @WebResult(name = "ProcessCommunityEditRequestResult", targetNamespace = "http://roadnet.com/apex/")
    public org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.ProcessCommunityEditRequestResult processCommunityEditRequest(
        @WebParam(name = "regionContext", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.RegionContext regionContext,
        @WebParam(name = "args", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.ProcessCommunityEditRequestArgs args
    ) throws IMappingServiceProcessCommunityEditRequestListOfValidationFailureFaultMessage, IMappingServiceProcessCommunityEditRequestTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "UpdateArcs", action = "http://roadnet.com/apex/IMappingService/UpdateArcs")
    @Action(input = "http://roadnet.com/apex/IMappingService/UpdateArcs", output = "http://roadnet.com/apex/IMappingService/UpdateArcsResponse", fault = {@FaultAction(className = IMappingServiceUpdateArcsListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/UpdateArcsListOf_ValidationFailureFault"), @FaultAction(className = IMappingServiceUpdateArcsTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/UpdateArcsTransferErrorCodeFault")})
    @RequestWrapper(localName = "UpdateArcs", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.UpdateArcs")
    @ResponseWrapper(localName = "UpdateArcsResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.UpdateArcsResponse")
    @WebResult(name = "UpdateArcsResult", targetNamespace = "http://roadnet.com/apex/")
    public org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.UpdateArcsResults updateArcs(
        @WebParam(name = "regionContext", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.RegionContext regionContext,
        @WebParam(name = "arcsToUpdate", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.ArrayOfNetworkArc arcsToUpdate,
        @WebParam(name = "options", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.UpdateArcsOptions options
    ) throws IMappingServiceUpdateArcsListOfValidationFailureFaultMessage, IMappingServiceUpdateArcsTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "RetrieveMapDataRegionInfo", action = "http://roadnet.com/apex/IMappingService/RetrieveMapDataRegionInfo")
    @Action(input = "http://roadnet.com/apex/IMappingService/RetrieveMapDataRegionInfo", output = "http://roadnet.com/apex/IMappingService/RetrieveMapDataRegionInfoResponse", fault = {@FaultAction(className = IMappingServiceRetrieveMapDataRegionInfoListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/RetrieveMapDataRegionInfoListOf_ValidationFailureFault"), @FaultAction(className = IMappingServiceRetrieveMapDataRegionInfoTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/RetrieveMapDataRegionInfoTransferErrorCodeFault")})
    @RequestWrapper(localName = "RetrieveMapDataRegionInfo", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveMapDataRegionInfo")
    @ResponseWrapper(localName = "RetrieveMapDataRegionInfoResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveMapDataRegionInfoResponse")
    @WebResult(name = "RetrieveMapDataRegionInfoResult", targetNamespace = "http://roadnet.com/apex/")
    public org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.ArrayOfMapRegionInfoDto retrieveMapDataRegionInfo(
        @WebParam(name = "regionContext", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.RegionContext regionContext
    ) throws IMappingServiceRetrieveMapDataRegionInfoListOfValidationFailureFaultMessage, IMappingServiceRetrieveMapDataRegionInfoTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "RetrieveGeocodeCandidates", action = "http://roadnet.com/apex/IMappingService/RetrieveGeocodeCandidates")
    @Action(input = "http://roadnet.com/apex/IMappingService/RetrieveGeocodeCandidates", output = "http://roadnet.com/apex/IMappingService/RetrieveGeocodeCandidatesResponse", fault = {@FaultAction(className = IMappingServiceRetrieveGeocodeCandidatesListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/RetrieveGeocodeCandidatesListOf_ValidationFailureFault"), @FaultAction(className = IMappingServiceRetrieveGeocodeCandidatesTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/RetrieveGeocodeCandidatesTransferErrorCodeFault")})
    @RequestWrapper(localName = "RetrieveGeocodeCandidates", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveGeocodeCandidates")
    @ResponseWrapper(localName = "RetrieveGeocodeCandidatesResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveGeocodeCandidatesResponse")
    @WebResult(name = "RetrieveGeocodeCandidatesResult", targetNamespace = "http://roadnet.com/apex/")
    public com.roadnet.apex.datacontracts.ArrayOfGeocodeResult retrieveGeocodeCandidates(
        @WebParam(name = "regionContext", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.RegionContext regionContext,
        @WebParam(name = "criteria", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.GeocodeCriteria criteria,
        @WebParam(name = "options", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.RetrieveGeocodeCandidateOptions options
    ) throws IMappingServiceRetrieveGeocodeCandidatesListOfValidationFailureFaultMessage, IMappingServiceRetrieveGeocodeCandidatesTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "RetrieveDeltaMapEdits", action = "http://roadnet.com/apex/IMappingService/RetrieveDeltaMapEdits")
    @Action(input = "http://roadnet.com/apex/IMappingService/RetrieveDeltaMapEdits", output = "http://roadnet.com/apex/IMappingService/RetrieveDeltaMapEditsResponse", fault = {@FaultAction(className = IMappingServiceRetrieveDeltaMapEditsListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/RetrieveDeltaMapEditsListOf_ValidationFailureFault"), @FaultAction(className = IMappingServiceRetrieveDeltaMapEditsTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/RetrieveDeltaMapEditsTransferErrorCodeFault")})
    @RequestWrapper(localName = "RetrieveDeltaMapEdits", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveDeltaMapEdits")
    @ResponseWrapper(localName = "RetrieveDeltaMapEditsResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveDeltaMapEditsResponse")
    @WebResult(name = "RetrieveDeltaMapEditsResult", targetNamespace = "http://roadnet.com/apex/")
    public org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.RetrieveDeltaMapEditsResult retrieveDeltaMapEdits(
        @WebParam(name = "regionContext", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.RegionContext regionContext,
        @WebParam(name = "firstChangeVersion", targetNamespace = "http://roadnet.com/apex/")
        java.lang.Integer firstChangeVersion
    ) throws IMappingServiceRetrieveDeltaMapEditsListOfValidationFailureFaultMessage, IMappingServiceRetrieveDeltaMapEditsTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "ApplyEdit", action = "http://roadnet.com/apex/IMappingService/ApplyEdit")
    @Action(input = "http://roadnet.com/apex/IMappingService/ApplyEdit", output = "http://roadnet.com/apex/IMappingService/ApplyEditResponse", fault = {@FaultAction(className = IMappingServiceApplyEditListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/ApplyEditListOf_ValidationFailureFault"), @FaultAction(className = IMappingServiceApplyEditTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/ApplyEditTransferErrorCodeFault")})
    @RequestWrapper(localName = "ApplyEdit", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.ApplyEdit")
    @ResponseWrapper(localName = "ApplyEditResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.ApplyEditResponse")
    public void applyEdit(
        @WebParam(name = "regionContext", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.RegionContext regionContext,
        @WebParam(name = "editRecordDto", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.NetworkEditRecord editRecordDto
    ) throws IMappingServiceApplyEditListOfValidationFailureFaultMessage, IMappingServiceApplyEditTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "ApplyArcUpdates", action = "http://roadnet.com/apex/IMappingService/ApplyArcUpdates")
    @Action(input = "http://roadnet.com/apex/IMappingService/ApplyArcUpdates", output = "http://roadnet.com/apex/IMappingService/ApplyArcUpdatesResponse", fault = {@FaultAction(className = IMappingServiceApplyArcUpdatesListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/ApplyArcUpdatesListOf_ValidationFailureFault"), @FaultAction(className = IMappingServiceApplyArcUpdatesTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/ApplyArcUpdatesTransferErrorCodeFault")})
    @RequestWrapper(localName = "ApplyArcUpdates", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.ApplyArcUpdates")
    @ResponseWrapper(localName = "ApplyArcUpdatesResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.ApplyArcUpdatesResponse")
    @WebResult(name = "ApplyArcUpdatesResult", targetNamespace = "http://roadnet.com/apex/")
    public org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.ApplyArcUpdatesResult applyArcUpdates(
        @WebParam(name = "regionContext", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.RegionContext regionContext,
        @WebParam(name = "criteria", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.ApplyArcUpdatesCriteria criteria,
        @WebParam(name = "options", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.ApplyArcUpdatesOptions options
    ) throws IMappingServiceApplyArcUpdatesListOfValidationFailureFaultMessage, IMappingServiceApplyArcUpdatesTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "UpdateRestrictedPath", action = "http://roadnet.com/apex/IMappingService/UpdateRestrictedPath")
    @Action(input = "http://roadnet.com/apex/IMappingService/UpdateRestrictedPath", output = "http://roadnet.com/apex/IMappingService/UpdateRestrictedPathResponse", fault = {@FaultAction(className = IMappingServiceUpdateRestrictedPathListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/UpdateRestrictedPathListOf_ValidationFailureFault"), @FaultAction(className = IMappingServiceUpdateRestrictedPathTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/UpdateRestrictedPathTransferErrorCodeFault")})
    @RequestWrapper(localName = "UpdateRestrictedPath", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.UpdateRestrictedPath")
    @ResponseWrapper(localName = "UpdateRestrictedPathResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.UpdateRestrictedPathResponse")
    @WebResult(name = "UpdateRestrictedPathResult", targetNamespace = "http://roadnet.com/apex/")
    public org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.UpdateRestrictedPathResult updateRestrictedPath(
        @WebParam(name = "regionContext", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.RegionContext regionContext,
        @WebParam(name = "travelPath", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.NetworkRestrictedPath travelPath,
        @WebParam(name = "options", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.UpdateRestrictedPathOptions options
    ) throws IMappingServiceUpdateRestrictedPathListOfValidationFailureFaultMessage, IMappingServiceUpdateRestrictedPathTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "RetrieveMapInfo", action = "http://roadnet.com/apex/IMappingService/RetrieveMapInfo")
    @Action(input = "http://roadnet.com/apex/IMappingService/RetrieveMapInfo", output = "http://roadnet.com/apex/IMappingService/RetrieveMapInfoResponse", fault = {@FaultAction(className = IMappingServiceRetrieveMapInfoListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/RetrieveMapInfoListOf_ValidationFailureFault"), @FaultAction(className = IMappingServiceRetrieveMapInfoTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/RetrieveMapInfoTransferErrorCodeFault")})
    @RequestWrapper(localName = "RetrieveMapInfo", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveMapInfo")
    @ResponseWrapper(localName = "RetrieveMapInfoResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveMapInfoResponse")
    @WebResult(name = "RetrieveMapInfoResult", targetNamespace = "http://roadnet.com/apex/")
    public org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.RetrieveMapInfoResult retrieveMapInfo(
        @WebParam(name = "regionContext", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.RegionContext regionContext
    ) throws IMappingServiceRetrieveMapInfoListOfValidationFailureFaultMessage, IMappingServiceRetrieveMapInfoTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "UpdateImpasse", action = "http://roadnet.com/apex/IMappingService/UpdateImpasse")
    @Action(input = "http://roadnet.com/apex/IMappingService/UpdateImpasse", output = "http://roadnet.com/apex/IMappingService/UpdateImpasseResponse", fault = {@FaultAction(className = IMappingServiceUpdateImpasseListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/UpdateImpasseListOf_ValidationFailureFault"), @FaultAction(className = IMappingServiceUpdateImpasseTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/UpdateImpasseTransferErrorCodeFault")})
    @RequestWrapper(localName = "UpdateImpasse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.UpdateImpasse")
    @ResponseWrapper(localName = "UpdateImpasseResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.UpdateImpasseResponse")
    public void updateImpasse(
        @WebParam(name = "regionContext", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.RegionContext regionContext,
        @WebParam(name = "impasseDto", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.ImpasseNode impasseDto
    ) throws IMappingServiceUpdateImpasseListOfValidationFailureFaultMessage, IMappingServiceUpdateImpasseTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "RetrieveRestrictedPathsAndPolygons", action = "http://roadnet.com/apex/IMappingService/RetrieveRestrictedPathsAndPolygons")
    @Action(input = "http://roadnet.com/apex/IMappingService/RetrieveRestrictedPathsAndPolygons", output = "http://roadnet.com/apex/IMappingService/RetrieveRestrictedPathsAndPolygonsResponse", fault = {@FaultAction(className = IMappingServiceRetrieveRestrictedPathsAndPolygonsListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/RetrieveRestrictedPathsAndPolygonsListOf_ValidationFailureFault"), @FaultAction(className = IMappingServiceRetrieveRestrictedPathsAndPolygonsTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/RetrieveRestrictedPathsAndPolygonsTransferErrorCodeFault")})
    @RequestWrapper(localName = "RetrieveRestrictedPathsAndPolygons", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveRestrictedPathsAndPolygons")
    @ResponseWrapper(localName = "RetrieveRestrictedPathsAndPolygonsResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveRestrictedPathsAndPolygonsResponse")
    @WebResult(name = "RetrieveRestrictedPathsAndPolygonsResult", targetNamespace = "http://roadnet.com/apex/")
    public org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.RetrieveRestrictedPathsAndPolygonsResults retrieveRestrictedPathsAndPolygons(
        @WebParam(name = "regionContext", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.RegionContext regionContext,
        @WebParam(name = "criteria", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.RetrieveTravelPathsAndPolygonsCriteria criteria,
        @WebParam(name = "options", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.RetrieveRestrictedPathsAndPolygonsOptions options
    ) throws IMappingServiceRetrieveRestrictedPathsAndPolygonsListOfValidationFailureFaultMessage, IMappingServiceRetrieveRestrictedPathsAndPolygonsTransferErrorCodeFaultMessage;

    @WebMethod(operationName = "RetrieveMapChangedAreas", action = "http://roadnet.com/apex/IMappingService/RetrieveMapChangedAreas")
    @Action(input = "http://roadnet.com/apex/IMappingService/RetrieveMapChangedAreas", output = "http://roadnet.com/apex/IMappingService/RetrieveMapChangedAreasResponse", fault = {@FaultAction(className = IMappingServiceRetrieveMapChangedAreasListOfValidationFailureFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/RetrieveMapChangedAreasListOf_ValidationFailureFault"), @FaultAction(className = IMappingServiceRetrieveMapChangedAreasTransferErrorCodeFaultMessage.class, value = "http://roadnet.com/apex/IMappingService/RetrieveMapChangedAreasTransferErrorCodeFault")})
    @RequestWrapper(localName = "RetrieveMapChangedAreas", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveMapChangedAreas")
    @ResponseWrapper(localName = "RetrieveMapChangedAreasResponse", targetNamespace = "http://roadnet.com/apex/", className = "com.roadnet.apex.RetrieveMapChangedAreasResponse")
    @WebResult(name = "RetrieveMapChangedAreasResult", targetNamespace = "http://roadnet.com/apex/")
    public org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.RetrieveMapChangedAreasResults retrieveMapChangedAreas(
        @WebParam(name = "regionContext", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.RegionContext regionContext,
        @WebParam(name = "dateTime", targetNamespace = "http://roadnet.com/apex/")
        javax.xml.datatype.XMLGregorianCalendar dateTime,
        @WebParam(name = "viewport", targetNamespace = "http://roadnet.com/apex/")
        com.roadnet.apex.datacontracts.Viewport viewport,
        @WebParam(name = "options", targetNamespace = "http://roadnet.com/apex/")
        org.datacontract.schemas._2004._07.roadnet_apex_server_services_mapping.RetrieveMapChangedAreasOptions options
    ) throws IMappingServiceRetrieveMapChangedAreasListOfValidationFailureFaultMessage, IMappingServiceRetrieveMapChangedAreasTransferErrorCodeFaultMessage;
}
